config/routes.rb
Rails.application.routes.draw do
  resources :fanfics
  devise_for :users
  resources :posts do
      resources :comentarios
   end
   root :to => "posts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :post
end

app/models/fanfic.rb
class Fanfic < ApplicationRecord
  belongs_to :user
  validates :titulo, :presence => true
  validates :genero, :presence => true
  validates :resumo, :presence => true, :length => { :minimum => 10 }
  validates :conteudo, :presence => true, :length => { :minimum => 10 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comentarios, dependent: :destroy
  validates :titulo, :presence => true
  validates :genero, :presence => true
  validates :resumo, :presence => true, :length => { :minimum => 10 }
  validates :conteudo, :presence => true, :length => { :minimum => 10 }

  scoped_search on: [:titulo, :genero]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :fanfics, dependent: :destroy
  has_many :posts, dependent: :destroy
    # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
         #, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  def create
    @post = Post.find(params[:post_id])
    @comentario = @post.comentarios.create(com_params)
    redirect_to post_path(@post)
   end
   def destroy
    @post = Post.find(params[:post_id])
    @comentario = @post.comentarios.find(params[:id])
    @comentario.destroy
    redirect_to post_path(@post)
  end
  def com_params
    params.require(:comentario).permit(:autor, :conteudo)
  end
end

app/controllers/fanfics_controller.rb
class FanficsController < ApplicationController
  before_action :set_fanfic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /fanfics
  # GET /fanfics.json
  def index
    @fanfics = Fanfic.all
  end

  # GET /fanfics/1
  # GET /fanfics/1.json
  def show
  end

  # GET /fanfics/new
  def new
    @fanfic = Fanfic.new
  end

  # GET /fanfics/1/edit
  def edit


  end

  # POST /fanfics
  # POST /fanfics.json
  def create
    @fanfic = Fanfic.new(fanfic_params)

    respond_to do |format|
      if @fanfic.save
        format.html { redirect_to @fanfic, notice: 'Fanfic was successfully created.' }
        format.json { render :show, status: :created, location: @fanfic }
      else
        format.html { render :new }
        format.json { render json: @fanfic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fanfics/1
  # PATCH/PUT /fanfics/1.json
  def update
    respond_to do |format|
      if @fanfic.update(fanfic_params)
        format.html { redirect_to @fanfic, notice: 'Fanfic was successfully updated.' }
        format.json { render :show, status: :ok, location: @fanfic }
      else
        format.html { render :edit }
        format.json { render json: @fanfic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fanfics/1
  # DELETE /fanfics/1.json
  def destroy
    @fanfic.destroy
    respond_to do |format|
      format.html { redirect_to fanfics_url, notice: 'Fanfic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fanfic
      @fanfic = Fanfic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fanfic_params
      params.require(:fanfic).permit(:titulo, :genero, :status, :resumo, :conteudo)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @q = Post.ransack(params[:q].try(:merge, m: params[:combinator]))
    @posts = @q.result
    #@posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :genero, :resumo, :conteudo)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:admin, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/fanfics_helper.rb
module FanficsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comentarios/_comentario.html.erb
<%= comentario.autor %>
<%= comentario.conteudo %>
<%= time_ago)in_words(comentarios.creat_at) %>

app/views/comentarios/_form.html.erb
<%= form_for([@post, @post.comentarios.build]) do |f| %>
  <p>
    <%= f.label :autor %>
    <%= f.text_field :autor %>
  </p>
  <p>
    <%= f.label :conteudo %><br>
    <%= f.text_area :conteudo %>
  </p>
  <br>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Autor</th>
      <th>Conteudo</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.autor %></td>
        <td><%= comentario.conteudo %></td>
        <td><%= comentario.post_id %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Autor:</strong>
  <%= @comentario.autor %>
</p>

<p>
  <strong>Conteudo:</strong>
  <%= @comentario.conteudo %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comentario.post_id %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>

app/views/fanfics/_form.html.erb
<%= form_with(model: fanfic, local: true) do |form| %>
  <% if fanfic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fanfic.errors.count, "error") %> prohibited this fanfic from being saved:</h2>

      <ul>
        <% fanfic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :genero %>
    <%= form.text_field :genero %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :resumo %>
    <%= form.text_area :resumo %>
  </div>

  <div class="field">
    <%= form.label :conteudo %>
    <%= form.text_area :conteudo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fanfics/edit.html.erb
<h1>Editing Fanfic</h1>

<%= render 'form', fanfic: @fanfic %>

<%= link_to 'Show', @fanfic %> |
<%= link_to 'Back', fanfics_path %>

app/views/fanfics/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>YourFanfic</title>

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="css/clean-blog.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<header class="intro-header" style="background-image: url('img/fanfic.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1>Envie sua Fanfic</h1>
                        <h2 class="subheading">Divida sua história conosco</h2>

                    </div>
                </div>
            </div>
        </div>
    </header>

    <% if current_user %>
      <h3><%= link_to 'Nova Fanfic', new_fanfic_path %></h3>
    <% end %>
<br>
<h3>Suas fanfic enviadas</h3>
<table>
  <thead>
    <tr>
      <h3><th>Titulo</th></h3>
      <h3><th>Genero</th></h3>
      <h3><th>Status</th></h3>
      <h3><th>Resumo</th></h3>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fanfics.each do |fanfic| %>
      <tr>
        <td><%= fanfic.titulo %></td>
        <td><%= fanfic.genero %></td>
        <td><%= fanfic.status %></td>
        <td><%= fanfic.resumo %></td>

        <td><%= link_to 'Ler', fanfic %></td>
        <% if current_user %>
          <td><%= link_to 'Editar', edit_fanfic_path(fanfic) %></td>
          <td><%= link_to 'Excluir', fanfic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/fanfics/new.html.erb
<h1>New Fanfic</h1>

<%= render 'form', fanfic: @fanfic %>

<%= link_to 'Back', fanfics_path %>

app/views/fanfics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @fanfic.titulo %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @fanfic.genero %>
</p>

<p>
  <strong>Status:</strong>
  <%= @fanfic.status %>
</p>

<p>
  <strong>Resumo:</strong>
  <%= @fanfic.resumo %>
</p>

<p>
  <strong>Conteudo:</strong>
  <%= @fanfic.conteudo %>
</p>

<%= link_to 'Edit', edit_fanfic_path(@fanfic) %> |
<%= link_to 'Back', fanfics_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>

    <title>YourFanfic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    </head>

<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/index.html">YourFanfic</a>
    </div>
    <ul class="nav navbar-nav">
    <%# <li><%= link_to "Home", home_path %></li>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <p class="navbar-text float-right">


  <body>
    <% if user_signed_in? %>
      Logado como: <strong><%= current_user.email %></strong>.
      <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>

    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :genero %>
    <%= form.text_field :genero %>
  </div>

  <div class="field">
    <%= form.label :resumo %>
    <%= form.text_area :resumo %>
  </div>

  <div class="field">
    <%= form.label :conteudo %>
    <%= form.text_area :conteudo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>YourFanfic</title>

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="css/clean-blog.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<header class="intro-header" style="background-image: url('img/hero-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1>Fanfics</h1>
                        <h2 class="subheading">Encontre uma fanfic da sua preferência</h2>

                    </div>
                </div>
            </div>
        </div>
    </header>

<%= search_form_for @q do |f| %>
  <%= f.label :titulo_cont %>
  <%= f.search_field :titulo_cont %>

  <%= f.select :combinator,[['E', 'and'],['OU', 'or']] %>
  <%= f.label :genero_cont %>
  <%= f.search_field :genero_cont %>

  <%= f.submit %>
<% end %>
<br>

<h1>Posts</h1>

<table>
  <thead>

    <tr>
      <th><%= sort_link(@q, :titulo) %></th>
      <th><%= sort_link(@q, :genero) %></th>
      <th>Resumo</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% for post in @posts.reverse %>
      <tr>
        <td><%= post.titulo %></td>
        <td><%= post.genero %></td>
        <td><%= post.resumo %></td>

        <td><%= link_to 'Ver mais', post %></td>
        <% if current_user && current_user.admin %>
        <td><%= link_to 'Editar', edit_post_path(post) %></td>
        <td><%= link_to 'Excluir', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user && current_user.admin %>
<h3><%= link_to 'Novo Post', new_post_path %></h3>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @post.titulo %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @post.genero %>
</p>

<p>
  <strong>Resumo:</strong>
  <%= @post.resumo %>
</p>

<p>
  <strong>Conteudo:</strong>
  <%= simple_format (@post.conteudo) %>
</p>
<br>
<h2>Comentários</h2>
<% @post.comentarios.each do |comentario| %>

  <p>
    <b>Autor:</b>
    <%= comentario.autor %>
  </p>

  <p>
    <b>Comentario:</b>
    <%= comentario.conteudo %>
  </p>
  <% if current_user && current_user.admin %>
    <%= link_to 'Excluir', [comentario.post, comentario], method: :delete %>
  <% end %>
<hr />


<% end %>

<h2>Adicione um comentario:</h2>
<%= form_for([@post, @post.comentarios.build]) do |f| %>
  <div class="field">
    <%= f.label :autor %><br />
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :conteudo %><br />
    <%= f.text_area :conteudo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<br />

<% if current_user && current_user.admin %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :admin %>
    <%= form.check_box :admin %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Admin</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.admin %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>